three seconds is better
rustamturnik/Test1 pull request #1
Opened 2019-01-11 12:17 UTC by jalilovr

Hello, please apply my changes.
I`m increased smart-blink from 1 sec to 3 sec.
What do you think about this?

2019-01-11 13:17 UTC, rustamturnik requested changes
please correct you changes

2019-01-11 13:17 UTC, rustamturnik commented on Main.txt
> +Slow-Blink
Ok,please write smart blink time, after this i merge you chages in my master branch,

2019-01-11 13:25 UTC, jalilovr commented on Main.txt
> +Slow-Blink
Ok

2019-03-10 11:55 UTC, jalilovr commented
Soon i can  push my changes

2019-03-10 12:23 UTC, merged